# Ansible Playbook for installing a full TV 2 - Sofie 

- name: Select Sofier Server hosts from hosts file
  hosts: sofieserver
  become: yes

  tasks:
    # Install apt:
    - name: Install aptitude using apt
      apt: 
        name: aptitude 
        state: latest 
        update_cache: yes 
        force_apt_get: yes

    # Install Docker-CE and requirements:
    - name: Install required system packages
      apt: 
        name: {{ item }} 
        state: latest 
        update_cache: yes
      loop: [ 
        'apt-transport-https', 
        'ca-certificates', 
        'curl', 
        'software-properties-common', 
        'python3-pip', 
        'virtualenv', 
        'python3-setuptools'
      ]
  
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: 
        update_cache: yes 
        name: docker-ce 
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create a network
      docker_network:
        name: sofie

    # Install Nginx
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    # Configure nginx and restart
    - name: Copy Nginx settings
      copy:
        src: files/nginx.cinf
        dest: /etc/nginx/
        owner: root
        group: root
        mode: 0644 

    - name: restart nginx
      service:
        name: nginx
        state: restart

    # Pull dockerimages:

    - name: pull Sofie Core
      docker_images:
        name: olzzon/tv-automation-server-core:{{ CORE_TAG }}

    - name: pull Sofie iNews Gateway
      docker_images:
        name: olzzon/tv2-inews-ftp-gateway:{{ INEWS_TAG }}
  
    - name: pull Sofie Playout Gateway
      docker_images:
        name: olzzon/tv-automation-playout-gateway:{{ PLAYOUT_TAG }}
    
    - name: pull Sisyfos
      docker_images:
        name: olzzon/sisyfos-audio-controller:{{ SISYFOS_TAG }}



    # Run images:
    - name: Run Core
      docker_container:
        name: server-core
        image: olzzon/tv-automation-server-core:{{ CORE_TAG }}
        state: reloaded
        ports:
          - "127.0.0.1:8080:80/tcp"
        volumes:
          - "/opt/coredisk:/opt/coredisk"
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: {{ TIMEZONE }}
          MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
          MONGO_URL: "mongodb://mongo:27017/sofie"
          ROOT_URL: "http://$TODO: HOSTNAME"
          PORT: 80
          HTTP_FORWARDED_COUNT: 1