# Ansible Playbook for installing a full TV 2 - Sofie 

- name: Select Sofier Server hosts from hosts file
  hosts: sofieserver
  become: yes

  tasks:
    # Install apt:
    - name: Install aptitude using apt
      apt: 
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    # Install Docker-CE and requirements:
    - name: Install required system packages
      apt: 
        name: "{{ item }}" 
        state: latest 
        update_cache: yes
      loop: [ 
        'apt-transport-https', 
        'ca-certificates', 
        'curl', 
        'software-properties-common', 
        'python3-pip', 
        'virtualenv', 
        'python3-setuptools'
      ]
  
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: 
        update_cache: yes 
        name: docker-ce 
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create a network
      docker_network:
        name: sofie

    # Install and configure Nginx
    - name: Install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    - name: Copy nginx settings
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/
        owner: root
        group: root
        mode: 0644 

    - name: restart nginx
      service:
        name: nginx
        state: restart

    # Install and configure Filebeat:
    - name: Update apt and install filebeat
      apt: 
        update_cache: yes 
        name: filebeat
        state: latest

    - name: Copy filebeat settings
      copy:
        src: files/filebeat.yml
        dest: /etc/filebeat/
        owner: root
        group: root
        mode: 0644 

    - name: Edit ip adress filebeat in config file
      lineinfile:
        dest: /etc/filebeat/filebeat.yml
        regexp: 'hosts: ["X.X.X.X:9200"]'
        line: 'hosts: ["{{ ELASTIC_IP }}:9200"]'
        state: present
  
    - name: restart filebeat
      service:
        name: filebeat
        state: restart

    # Pull dockerimages:

    - name: Pull MongoDb
      docker_image:
        name: mongo:{{ MONGO_TAG }}

    - name: pull Sofie Core
      docker_image:
        name: olzzon/tv-automation-server-core:{{ CORE_TAG }}

    - name: pull Sofie iNews Gateway
      docker_image:
        name: olzzon/tv2-inews-ftp-gateway:{{ INEWS_TAG }}
  
    - name: pull Sofie Playout Gateway
      docker_image:
        name: olzzon/tv-automation-playout-gateway:{{ PLAYOUT_TAG }}
    
    - name: pull Sisyfos
      docker_image:
        name: olzzon/sisyfos-audio-controller:{{ SISYFOS_TAG }}

    # Spin up images:
    
    # TODO: MongoDB  Replicaset: --replSet rs0
    - name: Run MongoDB
      docker_container:
        name: mongo
        image: mongo:{{ MONGO_TAG }}
        state: reloaded
        ports:
          - "127.0.0.1:27017:27017"
        volumes:
          - "/opt/coredisk:/opt/coredisk"
          - "/opt/mongo/backup:/data/backup"
          - "/etc/timezone:/etc/timezone:ro"
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: "{{ TIMEZONE }}"
          MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
          MONGO_URL: "mongodb://mongo:27017/sofie"
          ROOT_URL: "http://{{ HOSTNAME }}"
          PORT: 80
          HTTP_FORWARDED_COUNT: 1

    - name: Run Core
      docker_container:
        name: server-core
        image: olzzon/tv-automation-server-core:{{ CORE_TAG }}
        state: reloaded
        ports:
          - "127.0.0.1:8080:80/tcp"
        volumes:
          - "/opt/coredisk:/opt/coredisk"
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: "{{ TIMEZONE }}"
          MONGO_OPLOG_URL: "mongodb://mongo:27017/local"
          MONGO_URL: "mongodb://mongo:27017/sofie"
          ROOT_URL: "http://{{ HOSTNAME }}"
          PORT: 80
          HTTP_FORWARDED_COUNT: 1

    - name: Run iNews Gateway
      docker_container:
        name: inews-gateway
        image: olzzon/tv2-inews-ftp-gateway:{{ CORE_TAG }}
        state: reloaded
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: "{{ TIMEZONE }}"
          CORE_HOST: "server-core"
          CORE_PORT: 80
          DEVICE_ID: "{{ HOSTNAME }}"
          DEVICE_TOKEN: "{{ TOKEN }}"

    - name: Run Playout Gateway
      docker_container:
        name: playout-gateway
        image: olzzon/tv-automation-playout-gateway:{{ CORE_TAG }}
        state: reloaded
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: "{{ TIMEZONE }}"
          CORE_HOST: "server-core"
          CORE_PORT: 80
          DEVICE_ID: "{{ HOSTNAME }}"
          DEVICE_TOKEN: "{{ TOKEN }}"

    - name: Run Sisyfos
      docker_container:
        name: server-core
        image: olzzon/tv-automation-server-core:{{ CORE_TAG }}
        state: reloaded
        ports:
          - "1176:1176"
          - "5255:5255"
          - "5255:5255/udp"
        volumes:
          - "/opt/sisyfos-audio-controller:/opt/sisyfos-audio-controller/storage"
        restart_policy: always
        network_mode: "sofie"
        env:
          TZ: "{{ TIMEZONE }}"
          loggerIp: "{{ ELASTIC_IP }}"
          loggerPort: "{{ ELASTIC_PORT }}"