- name: Setup Sofie Deployment Server
  hosts: localhost
  become: yes

  tasks:
    - name: Pull docker image
      docker_image:
        force: yes
        source: pull
        name: "{{ SOFIE_DEPLOYMENT_SERVER_IMAGE }}:{{ SOFIE_DEPLOYMENT_SERVER_TAG }}"

    - name: Run docker image
      docker_container:
        name: deployment-server
        image: "{{ SOFIE_DEPLOYMENT_SERVER_IMAGE }}:{{ SOFIE_DEPLOYMENT_SERVER_TAG }}"
        state: started
        restart_policy: always
        ports:
          - "80:8080"
        volumes:
          - "/usr/local/home/cdserver/.ssh/id_rsa:/usr/src/app/id_rsa"
        env:
          SSH_HOST: "172.17.0.1"
          SSH_USER: "cdserver"
          SSH_PRIVATE_KEY: "/usr/src/app/id_rsa"
          SSH_CWD: "/usr/local/home/ansible"
          RUN_ANSIBLE_PLAYBOOK: "./ansible-production.sh"
