# Ansible Playbook setting up Sofie Portal

- name: Setup user web portal
  hosts: all
  become: yes
  tasks:

    - name: Create a webportal docker network
      docker_network:
        name: webportal
    
    - name: Copy nginx settings
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /opt/web-portal/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy webportal settings
      ansible.builtin.template:
        src: files/settings.json.j2
        dest: /opt/web-portal/settings.json
        owner: root
        group: root
        mode: 0644

    - name: Copy webportal users
      ansible.builtin.template:
        src: files/users.json.j2
        dest: /opt/web-portal/users.json
        owner: root
        group: root
        mode: 0644

    - name: Pull nginx docker image
      docker_image:
        source: pull
        name: nginx:latest
      tags:
        - webportalnginx

    - name: Sofie portal nginx proxy
      docker_container:
        restart: true
        name: nginx
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - "/opt/web-portal/nginx.conf:/etc/nginx/nginx.conf"
        restart_policy: always
        network_mode: "webportal"
      tags:
        - webportalnginx

    - name: Pull portal app image
      docker_image:
        source: pull
        name: "{{SOFIE_PORTAL_IMAGE}}:{{ SOFIE_PORTAL_TAG }}" 
      tags:
        - webportal

    - name: Make sure webportal is not running
      docker_container:
        name: sofie-portal
        state: absent

    - name: Sofie portal App
      docker_container:
        restart: true
        name: sofie-portal
        image: "{{SOFIE_PORTAL_IMAGE}}:{{ SOFIE_PORTAL_TAG }}"
        ports:
          - "3000/tcp"
        volumes:
          - "/opt/web-portal/settings.json:/opt/tv2-sofie-portal/build/storage/settings.json"
          - "/opt/web-portal/users.json:/opt/tv2-sofie-portal/build/storage/users.json"
        restart_policy: always
        network_mode: "webportal"
      tags:
        - webportal
