- name: Setup sofie mongodb database
  hosts: all
  become: yes

  tasks:
    - name: Creates /opt/coredisk
      file:
        path: /opt/coredisk
        state: directory
        owner: root
        group: root
        mode: 0644
  
    - name: Creates /opt/mongo/backup
      file:
        path: /opt/mongo/backup
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Creates /opt/mongo/conf
      file:
        path: /opt/mongo/conf
        state: directory
        owner: root
        group: root
        mode: 0644
    
    - name: Copy mongodb conf
      ansible.builtin.template:
        src: files/mongod.conf.j2
        dest: /opt/mongo/conf/mongod.conf
        owner: root
        group: root
        mode: 0644

    - name: Pull MongoDb
      docker_image:
        source: pull
        name: mongo:{{ MONGO_TAG }}
      tags:
        - sofiemongo

    - name: Run MongoDB
      docker_container:
        name: mongo
        hostname: mongodb
        image: mongo:{{ MONGO_TAG }}
        state: started
        ports:
          - "0.0.0.0:27017:27017"
        volumes:
          - "/opt/coredisk:/opt/coredisk"
          - "/opt/mongo/backup:/data/backup"
          - "/etc/timezone:/etc/timezone:ro"
          - "/opt/mongo/conf/mongod.conf:/etc/mongod.conf"
        restart_policy: always
        network_mode: "sofie"
        # command: "mongod"
        container_default_behavior: compatibility
      tags:
        - sofiemongo