- name: Setup sofie mongodb database
  hosts: all
  become: yes

  tasks:
    - name: Creates /opt/coredisk
      file:
        path: /opt/coredisk
        state: directory
        owner: root
        group: root
        mode: 0644
  
    - name: Creates /opt/mongo/backup
      file:
        path: /opt/mongo/backup
        state: directory
        owner: root
        group: root
        mode: 0644
    
    - name: Pull MongoDb
      docker_image:
        source: pull
        name: mongo:{{ MONGO_TAG }}
      tags:
        - sofiemongo

    - name: Run MongoDB
      docker_container:
        name: mongo
        hostname: mongodb
        image: mongo:{{ MONGO_TAG }}
        state: started
        ports:
          - "0.0.0.0:27017:27017"
        volumes:
          - "/opt/coredisk:/opt/coredisk"
          - "/opt/mongo/backup:/data/backup"
          - "/etc/timezone:/etc/timezone:ro"
        restart_policy: always
        network_mode: "sofie"
        command: "mongod --replSet rs0"
        container_default_behavior: compatibility
      tags:
        - sofiemongo

    - name: Pause for 20 seconds for mongoDB to start up
      pause:
        seconds: "20"

    - name: rs.initiate
      shell: "docker exec mongo mongo --quiet --eval 'rs.initiate()'"

