- name: Setup sofie blueprints
  hosts: all
  become: yes

  tasks:
    - name: Creates /opt/sofie-blueprints/nginx
      file:
        path: /opt/sofie-blueprints/nginx
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: pull Sofie Blueprints
      docker_image:
        source: pull
        name: olzzon/tv2-sofie-blueprints-inews:{{ BLUEPRINTS_TAG }}
      tags:
        - sofieblueprints

    - name: Run Sofie Blueprints
      docker_container:
        name: blueprint-build
        image: olzzon/tv2-sofie-blueprints-inews:{{ BLUEPRINTS_TAG }}
        state: started
        network_mode: "sofie"
        env:
          SERVER: "{{ SOFIE_CORE }}"
        volumes:
          - "/opt/sofie-blueprints/nginx:/opt/blueprints/nginx"
        container_default_behavior: no_defaults
      tags:
        - sofieblueprints