- name: Setup Sofie Health Monitor
  hosts: health
  become: yes

  tasks:
    - name: Create data folder
      file:
        path: /opt/sofie-health-monitor/data
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Generate hosts.json
      ansible.builtin.template:
        src: files/hosts.json.j2
        dest: /opt/sofie-health-monitor/data/hosts.json
        owner: root
        group: root
        mode: 0644
      vars:
        TARGETS: "{{ groups['qbox'] + groups['afvd'] }}"

    - name: Pull docker image
      docker_image:
        force_source: yes
        source: pull
        name: "{{ SOFIE_HEALTH_MONITOR_IMAGE }}:{{ SOFIE_HEALTH_MONITOR_TAG }}"

    - name: Run docker image
      docker_container:
        name: health-monitor
        image: "{{ SOFIE_HEALTH_MONITOR_IMAGE }}:{{ SOFIE_HEALTH_MONITOR_TAG }}"
        state: started
        restart_policy: always
        volumes:
          - "/opt/sofie-health-monitor/data:/usr/src/app/data"
        ports:
          - "80:8080"
